<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Marque;
use App\Models\Voiture;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class VoitureSeeder extends Seeder
{
    public function run(): void
    {
        $voitures = [
            [
                'titre'        => 'Toyota Corolla 2020',
                'description'  => 'Berline japonaise fiable et économique. Climatisation, vitres électriques, régulateur de vitesse. Parfaite pour la ville et les longues distances.',
                'prix_ariary'  => 45_000_000,
                'annee'        => 2020,
                'kilometrage'  => 35_000,
                'etat'         => 'occasion',
                'couleur'      => 'Blanc Nacré',
                'carburant'    => 'essence',
                'transmission' => 'automatique',
                'places'       => 5,
                'puissance_cv' => 132,
                'is_featured'  => true,
                'category'     => 'berline',
                'marque'       => 'toyota',
                'image'        => 'voitures/toyota-corolla-2020.png',
            ],
            [
                'titre'        => 'Toyota Land Cruiser Prado 2019',
                'description'  => 'SUV robuste tout terrain idéal pour Madagascar. 4x4 permanent, toit ouvrant, cuir, GPS. Le roi des routes difficiles.',
                'prix_ariary'  => 120_000_000,
                'annee'        => 2019,
                'kilometrage'  => 68_000,
                'etat'         => 'occasion',
                'couleur'      => 'Gris Métallisé',
                'carburant'    => 'diesel',
                'transmission' => 'automatique',
                'places'       => 7,
                'puissance_cv' => 190,
                'is_featured'  => true,
                'category'     => 'suv',
                'marque'       => 'toyota',
                'image'        => 'voitures/toyota-prado-2019.png',
            ],
            [
                'titre'        => 'Mitsubishi L200 Pickup 2021',
                'description'  => 'Pickup double cabine puissant. Benne, 4x4, idéal pour les livraisons et le transport. Très populaire à Madagascar.',
                'prix_ariary'  => 82_000_000,
                'annee'        => 2021,
                'kilometrage'  => 28_000,
                'etat'         => 'occasion',
                'couleur'      => 'Noir',
                'carburant'    => 'diesel',
                'transmission' => 'manuelle',
                'places'       => 5,
                'puissance_cv' => 154,
                'is_featured'  => true,
                'category'     => 'pickup',
                'marque'       => 'mitsubishi',
                'image'        => 'voitures/mitsubishi-l200-2021.png',
            ],
            [
                'titre'        => 'Renault Clio 5 2022',
                'description'  => 'Citadine moderne et élégante. Faible consommation, facile à garer en ville. Système multimédia Android Auto / Apple CarPlay.',
                'prix_ariary'  => 38_000_000,
                'annee'        => 2022,
                'kilometrage'  => 15_000,
                'etat'         => 'occasion',
                'couleur'      => 'Rouge Flamme',
                'carburant'    => 'essence',
                'transmission' => 'automatique',
                'places'       => 5,
                'puissance_cv' => 100,
                'is_featured'  => false,
                'category'     => 'citadine',
                'marque'       => 'renault',
                'image'        => 'voitures/renault-clio-2022.png',
            ],
            [
                'titre'        => 'BMW X5 2020',
                'description'  => 'SUV premium de luxe. Intérieur cuir, affichage tête haute, aide au stationnement, toit panoramique. Le summum du confort.',
                'prix_ariary'  => 185_000_000,
                'annee'        => 2020,
                'kilometrage'  => 42_000,
                'etat'         => 'occasion',
                'couleur'      => 'Blanc Alpin',
                'carburant'    => 'essence',
                'transmission' => 'automatique',
                'places'       => 5,
                'puissance_cv' => 265,
                'is_featured'  => true,
                'category'     => 'suv',
                'marque'       => 'bmw',
                'image'        => 'voitures/bmw-x5-2020.png',
            ],
            [
                'titre'        => 'Toyota Hilux 2023',
                'description'  => 'Pickup légendaire de dernière génération. Neuf, zéro kilomètre, garantie constructeur 3 ans. La référence en pickup.',
                'prix_ariary'  => 98_000_000,
                'annee'        => 2023,
                'kilometrage'  => 0,
                'etat'         => 'neuf',
                'couleur'      => 'Bleu Azur',
                'carburant'    => 'diesel',
                'transmission' => 'automatique',
                'places'       => 5,
                'puissance_cv' => 204,
                'is_featured'  => true,
                'category'     => 'pickup',
                'marque'       => 'toyota',
                'image'        => 'voitures/toyota-hilux-2023.png',
            ],
            [
                'titre'        => 'Mercedes-Benz C220 2021',
                'description'  => 'Berline allemande haut de gamme. Finition cuir AMG Line, système MBUX, phares LED. Élégance et performance.',
                'prix_ariary'  => 155_000_000,
                'annee'        => 2021,
                'kilometrage'  => 22_000,
                'etat'         => 'occasion',
                'couleur'      => 'Noir Obsidien',
                'carburant'    => 'diesel',
                'transmission' => 'automatique',
                'places'       => 5,
                'puissance_cv' => 194,
                'is_featured'  => false,
                'category'     => 'berline',
                'marque'       => 'mercedes',
                'image'        => 'voitures/mercedes-c220-2021.png',
            ],
            [
                'titre'        => 'Hyundai Tucson 2022',
                'description'  => 'SUV coréen moderne avec design avant-gardiste. Technologie embarquée avancée, hybride disponible, très économique.',
                'prix_ariary'  => 72_000_000,
                'annee'        => 2022,
                'kilometrage'  => 18_000,
                'etat'         => 'occasion',
                'couleur'      => 'Vert Forêt',
                'carburant'    => 'hybride',
                'transmission' => 'automatique',
                'places'       => 5,
                'puissance_cv' => 180,
                'is_featured'  => false,
                'category'     => 'suv',
                'marque'       => 'hyundai',
                'image'        => 'voitures/hyundai-tucson-2022.png',
            ],
            [
                'titre'        => 'Isuzu D-Max 2020',
                'description'  => 'Pickup robuste et fiable, idéal pour le transport. Moteur diesel économique, très solide pour les routes malgaches.',
                'prix_ariary'  => 65_000_000,
                'annee'        => 2020,
                'kilometrage'  => 55_000,
                'etat'         => 'occasion',
                'couleur'      => 'Argent',
                'carburant'    => 'diesel',
                'transmission' => 'manuelle',
                'places'       => 5,
                'puissance_cv' => 163,
                'is_featured'  => false,
                'category'     => 'pickup',
                'marque'       => 'isuzu',
                'image'        => 'voitures/isuzu-dmax-2020.png',
            ],
            [
                'titre'        => 'Peugeot 208 2023',
                'description'  => 'Citadine française neuve. Design moderne, i-Cockpit 3D, motorisation vive. Parfaite pour les déplacements urbains.',
                'prix_ariary'  => 42_000_000,
                'annee'        => 2023,
                'kilometrage'  => 0,
                'etat'         => 'neuf',
                'couleur'      => 'Bleu Vertigo',
                'carburant'    => 'essence',
                'transmission' => 'automatique',
                'places'       => 5,
                'puissance_cv' => 100,
                'is_featured'  => false,
                'category'     => 'citadine',
                'marque'       => 'peugeot',
                'image'        => 'voitures/peugeot-208-2023.png',
            ],
            [
                'titre'        => 'Toyota Avanza 2021',
                'description'  => 'Monospace 7 places idéal pour la famille. Économique, fiable, très populaire à Madagascar. Intérieur spacieux.',
                'prix_ariary'  => 48_000_000,
                'annee'        => 2021,
                'kilometrage'  => 32_000,
                'etat'         => 'occasion',
                'couleur'      => 'Blanc',
                'carburant'    => 'essence',
                'transmission' => 'manuelle',
                'places'       => 7,
                'puissance_cv' => 95,
                'is_featured'  => false,
                'category'     => 'monospace',
                'marque'       => 'toyota',
                'image'        => 'voitures/toyota-avanza-2021.png',
            ],
            [
                'titre'        => 'Nissan Navara 2022',
                'description'  => 'Pickup double cabine premium. Suspension Pro-4X, suspension indépendante, très confortable. Pour les aventuriers.',
                'prix_ariary'  => 88_000_000,
                'annee'        => 2022,
                'kilometrage'  => 20_000,
                'etat'         => 'occasion',
                'couleur'      => 'Gris Sombre',
                'carburant'    => 'diesel',
                'transmission' => 'automatique',
                'places'       => 5,
                'puissance_cv' => 190,
                'is_featured'  => true,
                'category'     => 'pickup',
                'marque'       => 'nissan',
                'image'        => 'voitures/nissan-navara-2022.png',
            ],
        ];

        foreach ($voitures as $data) {
            $category = Category::where('slug', $data['category'])->first();
            $marque   = Marque::where('slug', $data['marque'])->first();

            if (!$category || !$marque) continue;

            $slug = Str::slug($data['titre']);
            $slug = Voiture::where('slug', $slug)->exists()
                ? $slug . '-' . uniqid()
                : $slug;

            Voiture::firstOrCreate(['slug' => $slug], [
                'titre'        => $data['titre'],
                'slug'         => $slug,
                'description'  => $data['description'],
                'prix_ariary'  => $data['prix_ariary'],
                'annee'        => $data['annee'],
                'kilometrage'  => $data['kilometrage'],
                'etat'         => $data['etat'],
                'couleur'      => $data['couleur'],
                'carburant'    => $data['carburant'],
                'transmission' => $data['transmission'],
                'places'       => $data['places'],
                'puissance_cv' => $data['puissance_cv'],
                'is_featured'  => $data['is_featured'],
                'is_active'    => true,
                'images'       => isset($data['image']) ? [$data['image']] : null,
                'category_id'  => $category->id,
                'marque_id'    => $marque->id,
            ]);
        }
    }
}
